# Generated by Django 4.1.1 on 2022-09-19 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('мужсккой', 'мужской'), ('женский', 'женский')], max_length=8)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.photo')),
            ],
        ),
    ]
