# Generated by Django 4.1.1 on 2022-09-19 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.photo'),
        ),
    ]
