# Generated by Django 4.1.1 on 2022-09-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('мужской', 'мужской'), ('женский', 'женский')], max_length=8),
        ),
    ]
